### PR TITLE
Export printable type

### PR DESCRIPTION
**Pull request by fubhy**

### CODE REVIEW

**Comment by timostamm** [comment]
I felt tempted to make it public too. The rationale not to do so was to encourage keeping plugin code simple, and pass an `f: GeneratedFile` to helper functions. Can I ask about your use case?

**Comment by fubhy** [comment]
I'm writing a coupler helper functions in my generator plugin for which it would be great to access this type (to type input & output in a composable manner). 

It's not a big deal if you don't expose this type because I can also derive / infer it from `f.print` parameters but it would be a bit less "hacky" to be able to access it directly.

**Comment by fubhy** [comment]
I see your point though about passing around the file context everywhere. I'll have to think about that ...

It makes unit testing a bit less ergonomic tbh.

**Comment by fubhy** [comment]
Exactly. I need to generate a potentially long line (schema validation), sometimes also pull in an import, etc. so I was trying to split up the logic for that a bit without adding any newlines.

**Comment by timostamm** [comment]
Gotcha. Let's make it public!

Can I ask you to use the new export in [gencommon.ts](https://github.com/bufbuild/protobuf-es/blob/5490fef984969ea66e8ec6ced41b33097691b14a/packages/protoplugin/src/ecmascript/gencommon.ts#L33)?

**Comment by fubhy** [comment]
Yep. Also found some other places. I guess you would want to use it there too.

**Review by timostamm — APPROVED** [review]
LGTM!

**Pull request merged**
