### PR TITLE
Match typeUrls with leading slash in google.protobuf.Any

### PR DESCRIPTION
**Pull request by grod220**
Closes https://github.com/bufbuild/protobuf-es/issues/617

### CODE REVIEW

**Review by timostamm — COMMENTED** [review]
Thanks for the fix and the tests!

The Any class is actually generated by protoc-gen-es. Can you apply the change to the following two places in the plugin?

https://github.com/bufbuild/protobuf-es/blob/d1cb9fc3e774ffa46c8025301107a5a67922db69/packages/protoc-gen-es/src/typescript.ts#L289

https://github.com/bufbuild/protobuf-es/blob/d1cb9fc3e774ffa46c8025301107a5a67922db69/packages/protoc-gen-es/src/javascript.ts#L266

**Review by timostamm — APPROVED** [review]
LGTM!

**Comment by grod220** [comment]
Thanks for being so quick and responsive! 🎊

**Comment by timostamm** [comment]
Just released in [v1.5.0](https://github.com/bufbuild/protobuf-es/releases/tag/v1.5.0) 🙂

**Pull request merged**
